services:
  am2h-serverV1:
    image: "node:9.1-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - TZ=:/etc/localtime
    command: "npm start"
    volumes:
      - /opt/AM2H-ServerV1/:/home/node/app
      - /opt/AM2H-ServerV1/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"                                                                                                                                                                                                                                                                                  
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  am2h-timerV1:
    image: "node:9.1-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - TZ=:/etc/localtime
    command: "node --expose-gc startMqttTimer.js"
    volumes:
      - /opt/AM2H-ServerV1/:/home/node/app
      - /opt/AM2H-ServerV1/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"







